### PR TITLE
Update ammo.lua typo

### PR DESCRIPTION
**Pull request by GrybasTV**
Typo error was breaking script, ammo was used only once.

# Pull request template
> [!IMPORTANT]
> Please complete all fields. PRs will not be merged if any fields are incomplete. Be respectful, and keep in mind that it may take some time for your PR to be reviewed.
>
> Bear in mind refactors are up to the developers and not it's contributors after all we are the ones giving support when needed. if they are big changes I suggest you to release it under your name instead.

## Type of change

Bug fix (non-breaking change which fixes an issue)

### Motive for This Pull Request
Ammo does not work correctly
. 
### Provide a brief explanation of why these changes are being proposed and what they aim to achieve.
Fix typo 
### Explain the necessity of these changes and how they will impact the framework or its users.
Does not work. 

### Please describe the tests you have conducted to verify your changes. Provide instructions so we can reproduce these tests. Also, list any relevant details for your test configuration.

Tested with latest vorp scripts
 Tested with latest artifacts

## Notes if any
none

### CODE REVIEW

**Comment by outsider31000** [comment]
where is the typo? all i see is that you add spaces

**Comment by GrybasTV** [comment]
Spaces, but with these spaces ammo does not work.

**Comment by GrybasTV** [comment]
You can loud ammo once, after server restart these ammo are unusable.

**Comment by outsider31000** [comment]
And that's because of the spaces? sorry but there is no issues with spaces, they have comas for a reason.

**Comment by outsider31000** [comment]
if you have an issue create one with steps of reproduction, spaces arent an issue.

**Pull request closed without merging**
