### PR TITLE
Fix Throwable weapons bug

### PR DESCRIPTION
**Pull request by EnerGonix**
Fixed a bug were the throwable weapons were unusable

# Pull request template
> [!IMPORTANT]
> Please complete all fields. PRs will not be merged if any fields are incomplete. Be respectful, and keep in mind that it may take some time for your PR to be reviewed.
>
> Bear in mind refactors are up to the developers and not it's contributors after all we are the ones giving support when needed. if they are big changes I suggest you to release it under your name instead.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Motive for This Pull Request
explanation field

### Provide a brief explanation of why these changes are being proposed and what they aim to achieve.
explanation field

### Explain the necessity of these changes and how they will impact the framework or its users.
explanation field

### Please describe the tests you have conducted to verify your changes. Provide instructions so we can reproduce these tests. Also, list any relevant details for your test configuration.

- [x] Tested with latest vorp scripts
- [x] Tested with latest artifacts

## Notes if any
explanation field

### CODE REVIEW

**Comment by EnerGonix** [comment]
Fixed a bug were the throwable weapons where unusable. Now its fixed

**Comment by outsider31000** [comment]
why do we have a templafe for pull requests if you dont use it? 
also can you explain what issue you had ? i just used a WEAPON_MELEE_HATCHET and i can throw it no problem

your pull request is messing with ammo, while throwables are weapons?

**Comment by outsider31000** [comment]
the issues isnt fixed by removing the check,  the operator <= its whats wrong. I will close this and adjust it.

**Comment by EnerGonix** [comment]
The axe works but example the bollas does not

Enviado de Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by outsider31000** [comment]
yes because its a non ammo weapon, either way I have fixed it the operator was wrong. thanks

**Pull request closed without merging**
