### PR TITLE
Added crating cost for ammo and weapons

### PR DESCRIPTION
**Pull request by HonorAlterium**

### CODE REVIEW

**Comment by outsider31000** [comment]
did you make this as a config true or false? players already buy it from gunsmiths players this way its setting to buy it twice + materials if you can make config to use this feature or not

**Comment by HonorAlterium** [comment]
I can do it sure, it would be enough to leave craftcost at 0 to not use the function

**Comment by outsider31000** [comment]
Then just comment in those params that 0 will disable.

**Comment by HonorAlterium** [comment]
Like this? I tested it and works with a config to on/off the feature

**Comment by HonorAlterium** [comment]
There is still an error, I correct it and I'm done

**Pull request merged**
